name: Notify Teams on Dependabot PR

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Send notification to Teams
        env:
          TEAMS_WEBHOOK_URL: "<URL_TO_YOUR_TEAMS_WEBHOOK>"
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          repo_name="${{ github.repository }}"
          payload="{\"text\": \"Dependabot PR created in ${repo_name}: <a href='${pr_url}'>${pr_title}</a>\"}"
          curl -H "Content-Type: application/json" -d "$payload" "$TEAMS_WEBHOOK_URL"
